# Generated by Django 3.2.5 on 2021-07-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_auto_20210723_1739"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="created",
            field=models.DateTimeField(editable=False),
        ),
    ]
